service: microservices

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  webhook-api:
    handler: src/api/lambda.handler
    events:
      - http: 
          method: any
          path: /{proxy+}
          cors: true
          authorizer: aws_iam
  delivery:
    handler: src/delivery/lambda.handler
